name: Lighthouse
on: [pull_request]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-ruby@v1
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Cache Bundler
        uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: npm install && npm install -g @lhci/cli@0.6.x
      - run: bundle install
      - run: npm run build
      - run: lhci autorun --config=.github/lighthouse/lighthouserc.json
