name: Lighthouse
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-ruby@v1
      - run: npm install && npm install -g @lhci/cli@0.6.x
      - run: bundle install
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            **/node_modules
            **/.jekyll-cache
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: lhci autorun --config=.github/lighthouse/lighthouserc.json
