name: Page Speed Insights
on: [pull_request]
jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running Page Speed Insights
    steps:
      - uses: actions/checkout@v2
      - name: Page Speed Insights
        uses: JakePartusch/psi-action@v1
